schema_version: 1

context:
  version: "1.3.4"

package:
  name: e3sm-quickview
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/e3sm-quickview/e3sm_quickview-${{ version }}.tar.gz
  sha256: 0df61e5d98df8100752706ced66684a182e1ca01f7bf256f0fa3b2829860843c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - quickview = e3sm_quickview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - paraview
    - trame >=3.12
    - trame-vtk >=2.10
    - trame-vuetify >=3.1
    - pyproj >=3.6.1
    - netcdf4 >=1.6.5
    - trame-dataclass >=1.2
    - trame-components
    - trame-tauri >=0.6.2
    - pillow

tests:
  - python:
      imports:
        - e3sm_quickview
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - quickview --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-quickview/

extra:
  recipe-maintainers:
    - jourdain
    - psavery
    - alesgenova
