schema_version: 1

context:
  version: "2.8.5"

package:
  name: e3sm-quickview
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/94/92/3a68a6e15d54c74c98534923e9eceba2ccd0c91f510f4db2177a0438a2fb/e3sm_quickview-${{ version }}.tar.gz
  sha256: 316be4198a89d351f90be45b65427e45423cf2e00ad6f52599f33686f326a8fb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - quickview = e3sm_quickview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - paraview >=6
    - wslink >=2.5.7
    - trame >=3.13.2
    - trame-rca >=2.6
    - trame-vuetify >=3.1
    - pyproj >=3.6.1
    - netcdf4 >=1.6.5
    - trame-dataclass >=2.0.2
    - trame-components
    - trame-tauri >=0.6.2
    - trame-colormaps >=1.5.0
    - pillow

tests:
  - python:
      imports:
        - e3sm_quickview
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - quickview --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-quickview/

extra:
  recipe-maintainers:
    - huiwanpnnl
    - jourdain
    - psavery
    - alesgenova
