schema_version: 1

context:
  version: "2.9.1"

package:
  name: e3sm-quickview
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/7c/cb/25dd157717211129233f0cf93429a8e6ead82e9fab79f27ef18198f4ddf9/e3sm_quickview-${{ version }}.tar.gz
  sha256: 9189418a815c207955f1241bcf90d878e74ce190de5d92db2ef7bef77fde35b1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - quickview = e3sm_quickview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - paraview >=6
    - wslink >=2.5.7
    - trame >=3.13.2
    - trame-rca >=2.6
    - trame-vuetify >=3.1
    - pyproj >=3.6.1
    - netcdf4 >=1.6.5
    - trame-dataclass >=2.0.2
    - trame-components
    - trame-tauri >=0.6.2
    - trame-colormaps >=1.5.0
    - pillow

tests:
  - python:
      imports:
        - e3sm_quickview
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - quickview --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-quickview/

extra:
  recipe-maintainers:
    - huiwanpnnl
    - jourdain
    - psavery
    - alesgenova
