schema_version: 1

context:
  version: "2.9.4"

package:
  name: e3sm-quickview
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/23/4e/7d2da8152b982507697e6d8e211e59e6ae3f5d3188730b16bfd6ee06fe9f/e3sm_quickview-${{ version }}.tar.gz
  sha256: 94f88130af5e30d35001c069a3aae02f9e7aee5977ef618f76173b3be8dfe67c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - quickview = e3sm_quickview.app:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - paraview >=6
    - hdf5 <2
    - wslink >=2.5.7
    - trame >=3.13.2
    - trame-rca >=2.6
    - trame-vuetify >=3.1
    - pyproj >=3.6.1
    - netcdf4 >=1.6.5
    - trame-dataclass >=2.0.2
    - trame-components
    - trame-tauri >=0.6.2
    - trame-colormaps >=1.5.0
    - pillow

tests:
  - python:
      imports:
        - e3sm_quickview
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - quickview --help

about:
  summary: An application to explore/analyze data for atmosphere component for E3SM
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/e3sm-quickview/

extra:
  recipe-maintainers:
    - huiwanpnnl
    - jourdain
    - psavery
    - alesgenova
